package avachat.hired;

import org.junit.Test;

import static org.testng.Assert.*;

public class Assessment2Test {


    private static final String big1 = "UgBZmDnGFygWqJVFtzsHfQMjvnWvakeYSbqXaYYOsVXFMAlyoOmRlxmOyPjCYUTRtEOjFNvBjvXRpnLGrVmtzlGzwtBdxasoCXVVJNeRATqbrXVnBtdyJAVGiudoxLSOtumjfqBSRfQbGWtlgvhStLbPthmDJhlnmxtBEBRGUfbTlqbkgQdVEtJgqBOpiSWTAemvvStocbtlknHASjnMOjcaXjtpQDbLGWGsAEyCYmNzBfnFKyTrXjzPEoKIGMLICgQHOJtynwmFcHBQEijxopamrXSRVWLNjQTJFDoaVaDRqrFGVBAJFpLbxQFEhlwUPbKusJgzTysEOMJWyMZkDLUgXocVXYsvmgeHteowcWzIXNDrBYJlPiMZJKfjukBOkOVeESpiNBCWRiDKGCoAymoMAQzeQUWKaiaIvlFdHcWjezPDImPljEDWgzenbfEyKtORGDEhMyLGXdbHDyjnEOmlZMdqdcFoUdGdrhMPrbDZOGVYsLGslSfbBpSEfUUQdmaluCszagWQPEPgiwyaqbOHaikHcrILtVMCyruOGUmGDHynqvIfXVsEgRSoUminNSqzPaIjhbWaDAQXOPkhvoNwPuWDbaYtZFieqdWZRgLVsSsHVshXTJhRHpQsoBOaeXLwkAfvRdnMilEvYGBWLPTKMJnTWGofUvRLuyNbSjthRgHZLzRCdrpJZLpZtwZiHHkOyaFfSFoaIeHSVgholKqZclItKfuDSyTqaPMrjLFZwaNpFxzzbArroRqsXLQzkkYrOVuexpkJHUFJzRkcpjPGUFpAQLkTnEOWQAXbkEHBZIpQqqIsyUFDBkLFZXIvFrkMEHKDjSkdlOHevuFxrMfLKUbBOfXifrTQbajflnDkaAfKlXsIbEJAHyyWLBbmlfTdvEwdjccdDPtyuKMGPeXiOfnWpQnoxuWeHoVkoxzhRzmLtWwMYnKUJPJlQCtwoFAxLpcufKgobxQHamSONRBHLFWFCJMviVfnvCoACLrJDAhcVUMIfEUOQdiAUMIAVTMmpSQOvlxlZLPOsXLitZZbCEoqRbcksqrAxCzqMPVpKppZkVaxhSjVIrWslMWpqfqkTkCbATfvTMdySmYaVPCxzMyHyOuSrsMWmumOYLvkTyagfhhIqGIKnBRSTKvJovYUQzOZTPtgYyeaYmtqrYGWYMiprMICyBrToyHQMUYgZTAMxAkRJWhnsLwqtfeMOPkIiamSqkuotKQAZVlqwWCotksXxyNBkRxUxWtRKEIYGZYthrJnzfWqzUBpxDWjPvxquokvvrsgdCyMsXtfWDYuyZkCpvAKGxNYdbChzXiyuRZpSJZZVySmUlCIvGtTJKLAwbcELYRthqEvuXSmQyxtMOvsryOlsjpCJMNLrFjINmJBavDkKHajjCMWFXTqPprMpCdOzpKauiHFVftTRxvvPbcpnVbfoQWZySqLrFbffCCWUSdYhEaUJyccNibHODOSOcyyQfUnAVNnATqLyqrgpqKNQCYRiEHcNPBYjGdwJvRxxxVGzmXGmIqCrxrfIHHvtxRbMamkvnvexxsPWphoCHdLiKWLPsylhBBKpuKDwYbkCiqJbalqkKKIqdxbNvEjzNqwpotzlMlCJtyPyfBUfdMlsWKtMhYiWzgDUboKRzwqEwdUolwSIzRzefvyXbHQgWATUfEWMMeRBFFtcQChOxpRenQVeooyGaMoqtnpevCyryktmAaUAleTznhJmLZAtzvOPfCazUBUhUSBWwgukMbzNHWXldtWOlbSAPgkdlmAnXHDPKRVPEdEYMdfvMDzEYnLdsjgCBMOoNrlpkNDlxiuSKRhBwaySHEkdWGuHBpqJJqEWQKNNriDmkyesJujMgDFCNtPjFZpHJUpqLfpEoPJvKBvYihXwluJNLzstxBtoQdLpOxDzObcKDTaZXJXvnMHbNebKVPXcTSLAkikcNvEiXXSnzSDIOqDvlbuXpNzrxYdLlTIIKGRhVIIQzgcrhUqlPAWwfYwWSNDFnLrAgydKRnCuzwsTMUnMAUModZHUdaGvRSddXfCdXQUKZcCPDtoeCSskUZstoJvCLLcOekikMxTqDUugyuzGgrYENcfLgbtwwZwyVhDjdSnhNPBxrYkWGHAuJltKbzMAIWxurOVZokAitdogZcfTCkoPgDVHJOrqawwcXmQNsYVoHZEdDLiDtmzlpfuKxfpBkYXDaLJXJTPNBLVdJlwyArHmMGWkCBrTDWIIkWStQGUgpOOsETEegNDKavEMfytsyKJsfMvdoNkdFnDpncMYRekkEINZuhIYNbZMITVUxAAnReVCKDbOZDzCEAFNyXuLTBLFqqfKlwmOuiOqcGUEuUaHCJMpZYNxevlklQbOgLBdiYkvjMtDGVoRcSvvMxLsPxysrxNwenecqYwAvXhwjnuQrETimwZzHynnPRnupFmEGKJwRaGFbAFDVRkOlrnzEviJSEnAqgERqyjsZOEBmsBEdvQIgOpEzYTeowNtwjxqOTWKvxdztGhGkdWgJOZQEYBSTOWwnGmNNMyxKWyFUeLyAmeTUMFoDKvmrpcbcdBTGFrUJxJZkgYWyBjAUjQlnSFlxHImsyPKHwZqyIBcEojdsmFwYtWDVuKlBvBRalBsewIkmYtNqsnJkeZgCDuniSdLxCBJUBCsDwdmPROTCSnwmegleVjMHdOKQrnGoNMfzzkpWkGuqlEFgKilRUzdBThCGCmVAOYkxWkVAvHfAwfKUEzHgyMsiiGwtNJCzVxmJafLgdJQzbEfBFIshcYHKEyokxtVHdQOUfwMLvIdKLqXwQRVGNxYkmoDvsHxGXOMQYNOVYUVRHaRvhqAbOWzrVKfUdBQzysLTELyxvsfjRWJzXPStcKceGLBFdbuWFZDExIZDsiEazaAuCGMkZMnaPQXaGbPBfjbPtAZXSlKgFJTIdvSNqaciEBFDFkdRWpiFtBKvWZgOUAELXEnuUxKkFLaARwxiIipsDcnGUMIEwLqXyMxPqDgEtRiKtVSybHMQXUhIcsSyJnSitwbPFvGIIGLcPCOqwCKmEzYsGzqrjxjzfloeOvIDlYQgYgHmmMyYSXvLztVqFeBfsfAYZvbIUfyLpKPXDasqXEANFfbqNccTNkjaBWYvnyNjBFGlMmFlpyFMuUedZlUANdojavJGzvXRQCGhzFEopAhXGoMNsOxXeOuvCKNaIjpvJvCUSzUAqwRHYoEJKlAOQUBhOwbDiFLIAenjBSNtTCkqwKrVUqUzroXKEoqEERTomtqUpURZjyxeXCMVDJybKpHLWSocNBjuFCQUgvVFlflllJzbpgJAPakotmnfoArAEfhiMjyeCniwnecoDLzFKihkcHXLgaNSPKXMPsjOfJgBVMhGNPAPQetjIPzJfXNlzUsNDhioBFYquRaxaQSvJTVycCteuEAtjkpbtEKcRfEyPlumaUqMqQozRaFqkgTOEJXnLFFAHQFLxPsZrzqCKmqczdasAcOSPSTBCliFSaJyICRsGhUvyIivqowclCeeDoAsNEuaFTLeUDIkojCgPYhurjcoWhUjkhkrktbCWJBbXkcQydVXNmWMyzJJGFvoqMMlWqZwEXTWQdxepMEgLdkwMwqdxGeJgLLixyKrQkDMKLeXsorjgFgNPQTxKQKIpCITtLKsjztpPjwwixEjtIMQtMPxZqROXFiIGqTQHQNdgKNPRbkgjMIXVjBywaFnOgESYrkHnzaNtBbPKjRJjgojLgUzuRHMCdcouKthlxdGzILZaPUmvbxzKmEEdGJwUNCSdMmBmWAGicNCpVqJdGTgazMfiurGQDJZuXiHThQqVnbIHlt";

    @Test
    public void testAll() {


        assertEquals(Assessment2.solution("abcabcd"), 4);
        assertEquals(Assessment2.solution("ababcabcd"), 4);
        assertEquals(Assessment2.solution("abcdabcdefgabxyz"), 7);
        assertEquals(Assessment2.solution("abcdabcdefgabxyzcde"), 8);

        assertEquals(Assessment2.solution("abababab"), 2);
        assertEquals(Assessment2.solution("abcabcabc"), 3);
        assertEquals(Assessment2.solution("nndfddf"), 3);
        assertEquals(Assessment2.solution("abcd"), 4);
        assertEquals(Assessment2.solution("aaaaaaa"), 1);
        assertEquals(Assessment2.solution("a"), 1);
    }

    @Test
    public void testBig() {

        assertEquals(Assessment2.solution(big1), 25);
    }

}